# -*- coding: utf-8 -*-
"""COVID-19 Data Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SdajdpFltL7ehZDKGyO59wDT-S4LvxOh
"""

import pandas as pd

from google.colab import files
uploaded = files.upload()

df = pd.read_csv('owid-covid-data.csv')
df.head()

df.columns

df.info()

df = df[['location', 'date', 'total_cases', 'new_cases', 'total_deaths', 'new_deaths', 'population']]
df['date'] = pd.to_datetime(df['date'])  # Convert date to date format
df.dropna(subset=['location'], inplace=True)  # Remove empty rows

# Show cleaned data
df.head()

import matplotlib.pyplot as plt

# Filter for India and US
india = df[df['location'] == 'India']
us = df[df['location'] == 'United States']

# Plot
plt.figure(figsize=(10,5))
plt.plot(india['date'], india['total_cases'], label='India')
plt.plot(us['date'], us['total_cases'], label='US')
plt.xlabel("Date")
plt.ylabel("Total COVID Cases")
plt.title("India vs US - COVID-19 Total Cases Over Time")
plt.legend()
plt.show()

latest_date = df['date'].max()   # this finds the latest date in the dataset
latest_data = df[df['date'] == latest_date]  # filter only that date
latest_data.head()

top10 = latest_data.sort_values(by='total_cases', ascending=False).head(10)
top10

import matplotlib.pyplot as plt

plt.figure(figsize=(10,6))
plt.bar(top10['location'], top10['total_cases'], color='lightgreen')
plt.xticks(rotation=45)
plt.xlabel("Country")
plt.ylabel("Total COVID-19 Cases")
plt.title("Top 10 Countries by Total COVID-19 Cases")
plt.tight_layout()
plt.show()

print("Latest date in the dataset:", df['date'].max())

latest_data = df[df['date'] == df['date'].max()]
print("Number of rows for latest date:", len(latest_data))
latest_data[['location', 'total_cases']].head(10)

df_sorted = df.sort_values(by=['location', 'date'])

latest_valid_data = df_sorted.groupby('location').last().reset_index()

latest_valid_data[['location', 'total_cases']].head()

top10 = latest_valid_data.sort_values(by='total_cases', ascending=False).head(10)
print(top10[['location', 'total_cases']])

import matplotlib.pyplot as plt

plt.figure(figsize=(10,6))
plt.bar(top10['location'], top10['total_cases'], color='salmon')
plt.xticks(rotation=45)
plt.xlabel("Country")
plt.ylabel("Total COVID-19 Cases")
plt.title("Top 10 Countries by Total COVID-19 Cases")
plt.tight_layout()
plt.show()

india = df[df['location'] == 'India']

india_cases = india[['date', 'new_cases']]

plt.figure(figsize=(12,5))
plt.plot(india_cases['date'], india_cases['new_cases'], color='blue')
plt.title("Daily New COVID-19 Cases in India")
plt.xlabel("Date")
plt.ylabel("New Cases")
plt.grid(True)
plt.tight_layout()
plt.show()

latest_valid_data['fatality_rate'] = (latest_valid_data['total_deaths'] / latest_valid_data['total_cases']) * 100

latest_valid_data = latest_valid_data[(latest_valid_data['total_cases'] > 0) & (latest_valid_data['total_deaths'] > 0)]

top10_cfr = latest_valid_data.sort_values(by='fatality_rate', ascending=False).head(10)
print(top10_cfr[['location', 'fatality_rate']])

plt.figure(figsize=(10,6))
plt.bar(top10_cfr['location'], top10_cfr['fatality_rate'], color='red')
plt.xticks(rotation=45)
plt.xlabel("Country")
plt.ylabel("Case Fatality Rate (%)")
plt.title("Top 10 Countries by COVID-19 Fatality Rate")
plt.tight_layout()
plt.show()